[env:esp32cam]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32cam
framework = arduino
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
lib_deps =
    sandeepmistry/LoRa@^0.8.0
    links2004/WebSockets @ ^2.4.1
